name: habit_tracker2
description: A Flutter Habit Tracker app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter

    # ✅ Firebase latest
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.5.0

  # State Management
  provider: ^6.1.1

  # Local Storage
  shared_preferences: ^2.2.2

  # API for quotes
  http: ^1.1.2

  # UI & charts
  cupertino_icons: ^1.0.2
  flutter_staggered_grid_view: ^0.7.0
  flutter_charts: ^0.5.2
  fl_chart: ^0.69.0

  # Date formatting
  intl: ^0.18.1
  share_plus: ^7.0.0
  flutter_staggered_animations: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/Black.png
    - assets/White.png