// utils/local_quotes.dart
final Map<String, List<String>> localQuotes = {
  "Motivation": [
    "Do something today that your future self will thank you for.",
    "Little by little, one travels far.",
    "Don’t stop when you’re tired. Stop when you’re done.",
    "The harder you work for something, the greater you’ll feel when you achieve it.",
    "Dream it. Wish it. Do it.",
    "It always seems impossible until it’s done.",
    "Push yourself, because no one else is going to do it for you.",
    "Great things never come from comfort zones.",
    "The secret of getting ahead is getting started.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Small progress each day adds up to big results.",
  ],
  "Discipline": [
    "Discipline is the bridge between goals and accomplishment.",
    "Your habits will determine your future.",
    "Without discipline, success is impossible.",
    "Self-discipline begins with the mastery of your thoughts.",
    "Discipline weighs ounces, regret weighs tons.",
    "Motivation gets you going, but discipline keeps you growing.",
    "Discipline is choosing between what you want now and what you want most.",
    "Freedom is nothing else but a chance to be better — and discipline is the way.",
    "Consistency is harder when no one is clapping for you. Be disciplined anyway.",
    "Discipline is the silent power behind every great success.",
  ],
  "Success": [
    "Success is the sum of small efforts, repeated day in and day out.",
    "Success doesn’t come to you, you go to it.",
    "Great things never come from comfort zones.",
    "Success is not in what you have, but who you are.",
    "Opportunities don’t happen. You create them.",
    "Don’t wait for opportunity. Create it.",
    "The way to get started is to quit talking and begin doing.",
    "Success is walking from failure to failure with no loss of enthusiasm.",
    "Success usually comes to those who are too busy to be looking for it.",
    "There are no secrets to success. It is the result of preparation, hard work, and learning from failure.",
  ],
  "Habits": [
    "Small habits build big results.",
    "Your habits decide your tomorrow.",
    "We are what we repeatedly do.",
    "Good habits formed at youth make all the difference.",
    "Motivation is what gets you started. Habit is what keeps you going.",
    "Your future is hidden in your daily routine.",
    "Excellence is not an act, but a habit.",
    "Drop by drop fills the pot — so it is with habits.",
    "The chains of habit are too weak to be felt until they are too strong to be broken.",
    "Successful people are simply those with successful habits.",
  ],
  "Growth": [
    "Push yourself, because no one else is going to do it for you.",
    "Growth and comfort do not coexist.",
    "Difficulties strengthen the mind, as labor does the body.",
    "Be not afraid of growing slowly, be afraid only of standing still.",
    "The key to growth is the introduction of higher dimensions of consciousness into our awareness.",
    "Change is the end result of all true learning.",
    "The journey of growth begins the moment you decide to step forward.",
    "Don’t go through life, grow through life.",
    "Mistakes are proof that you’re trying and growing.",
    "Growth is painful. Change is painful. But nothing is as painful as staying stuck.",
  ],
  "Wisdom": [
    "The only true wisdom is in knowing you know nothing.",
    "Turn your wounds into wisdom.",
    "Knowing yourself is the beginning of all wisdom.",
    "A wise man learns more from his enemies than a fool from his friends.",
    "Knowledge speaks, but wisdom listens.",
    "Wisdom is the reward you get for a lifetime of listening.",
    "The invariable mark of wisdom is to see the miraculous in the common.",
    "Patience is the companion of wisdom.",
    "Silence is the sleep that nourishes wisdom.",
    "Wisdom begins in wonder.",
  ],
  "Mindfulness": [
    "The present moment is filled with joy and happiness.",
    "Mindfulness is the aware, balanced acceptance of the present experience.",
    "Feelings come and go like clouds in a windy sky. Conscious breathing is my anchor.",
    "Walk as if you are kissing the Earth with your feet.",
    "Mindfulness isn’t difficult, we just need to remember to do it.",
    "Breathe in deeply to bring your mind home to your body.",
    "Every morning we are born again. What we do today is what matters most.",
    "Be where you are, not where you think you should be.",
    "Peace comes from within. Do not seek it without.",
    "Smile, breathe, and go slowly.",
  ],
};
